# Generated by Django 5.2 on 2025-04-30 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='obra.construction')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='critical_path', to='cronograma.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cronograma.schedule')),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityConcept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_concepts', to='cronograma.activity')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_associations', to='catalogo.concept')),
            ],
            options={
                'unique_together': {('activity', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='CriticalPathActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_order', models.PositiveIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_path_inclusions', to='cronograma.activity')),
                ('critical_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_activities', to='cronograma.criticalpath')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('critical_path', 'activity')},
            },
        ),
    ]
