# Generated by Django 5.2 on 2025-05-01 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='construction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='obra.construction'),
        ),
    ]
