# Generated by Django 5.2 on 2025-04-29 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviada'), ('APPROVED', 'Aprobada'), ('PAID', 'Pagada')], default='DRAFT', max_length=20)),
            ],
            options={
                'verbose_name': 'Estimación',
                'verbose_name_plural': 'Estimaciones',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Por revisar'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_progress', to='catalogo.concept')),
            ],
            options={
                'verbose_name': 'Avance Físico',
                'verbose_name_plural': 'Avances Físicos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EstimationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimation_details', to='catalogo.concept')),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='avance.estimation')),
            ],
            options={
                'verbose_name': 'Detalle de Estimación',
                'verbose_name_plural': 'Detalles de Estimación',
                'ordering': ['estimation', 'concept'],
                'unique_together': {('estimation', 'concept')},
            },
        ),
    ]
