# Generated by Django 5.2 on 2025-05-01 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance', '0001_initial'),
        ('cronograma', '0001_initial'),
        ('obra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='based_on_schedule',
            field=models.BooleanField(default=False, help_text='Indica si se generó desde un cronograma'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='construction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='obra.construction'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_estimations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimation',
            name='is_planned',
            field=models.BooleanField(default=False, help_text='Indica si esta estimación es una planificación'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronograma.schedule'),
        ),
        migrations.AddField(
            model_name='estimationdetail',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronograma.activity'),
        ),
        migrations.AddField(
            model_name='estimationdetail',
            name='commitment_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('COMMITTED', 'Comprometido'), ('EXECUTED', 'Ejecutado'), ('DELAYED', 'Retrasado')], default='PENDING', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimationdetail',
            name='execution_date',
            field=models.DateField(blank=True, help_text='Fecha específica de ejecución planificada', null=True),
        ),
        migrations.AddField(
            model_name='estimationdetail',
            name='imported_from_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CommitmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('planned_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('ON_TRACK', 'En tiempo'), ('DELAYED', 'Retrasado'), ('ADVANCED', 'Adelantado'), ('COMPLETED', 'Completado')], default='ON_TRACK', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('estimation_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='avance.estimationdetail')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
    ]
