# Generated by Django 5.2 on 2025-05-01 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance', '0002_estimation_based_on_schedule_estimation_construction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commitmenttracking',
            options={'ordering': ['planned_date'], 'verbose_name': 'Seguimiento de Compromiso', 'verbose_name_plural': 'Seguimientos de Compromisos'},
        ),
        migrations.AddField(
            model_name='commitmenttracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitmenttracking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
