# Generated by Django 5.2 on 2025-06-29 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance', '0005_alter_physicalstatushistory_options'),
        ('obra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('blob_path', models.CharField(max_length=500, unique=True)),
                ('blob_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('thumbnail_blob_path', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail_blob_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('file_size_bytes', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=50)),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
                ('upload_status', models.CharField(choices=[('PENDING', 'Pendiente de subida'), ('UPLOADING', 'Subiendo'), ('COMPLETED', 'Completada'), ('FAILED', 'Falló')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_accuracy', models.FloatField(blank=True, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_make', models.CharField(blank=True, max_length=50, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=100, null=True)),
                ('exif_data', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='obra.construction')),
                ('physical_advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='avance.physical')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fotografía',
                'verbose_name_plural': 'Fotografías',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['upload_status'], name='avance_phot_upload__ada746_idx'), models.Index(fields=['construction', 'uploaded_at'], name='avance_phot_constru_09f3c3_idx'), models.Index(fields=['physical_advance'], name='avance_phot_physica_ead101_idx'), models.Index(fields=['uploaded_by', 'uploaded_at'], name='avance_phot_uploade_6fbb5b_idx')],
            },
        ),
    ]
