# Generated by Django 5.2 on 2025-09-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance', '0006_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physical',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
