# Generated by Django 5.2 on 2025-05-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_role_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('INSPECTOR', 'Inspector'), ('INVERSIONISTA', 'Inversionista'), ('DESARROLLADOR', 'Desarrollador'), ('CONTRATISTA', 'Contratista')], default='INSPECTOR', max_length=50),
        ),
    ]
