# Generated by Django 5.2 on 2025-04-30 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_role_alter_userrole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PLANNED', 'Planeada'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PLANNED', max_length=20)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionChangeControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modification', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('modification_date', models.DateField()),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_control', to='obra.construction')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de Cambios',
                'verbose_name_plural': 'Controles de Cambios',
                'ordering': ['-modification_date'],
            },
        ),
        migrations.CreateModel(
            name='UserConstruction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('asignation_date', models.DateField(auto_now_add=True)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_obras', to='obra.construction')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_obras', to='usuarios.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_obras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-Obra',
                'verbose_name_plural': 'Usuarios-Obras',
                'ordering': ['asignation_date'],
            },
        ),
    ]
