# Generated by Django 5.2 on 2025-07-27 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryCatalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Maquinaria',
                'verbose_name_plural': 'Catálogos de Maquinaria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkForceCatalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Fuerza Laboral',
                'verbose_name_plural': 'Catálogos de Fuerza Laboral',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('active_time', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('activity', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery', to='obra.construction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machinery', to=settings.AUTH_USER_MODEL)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machinery', to='recursos.machinerycatalog')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkForce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('activity', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforce', to='obra.construction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workforce', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workforce', to='recursos.workforcecatalog')),
            ],
            options={
                'verbose_name': 'Fuerza Laboral',
                'verbose_name_plural': 'Fuerzas Laborales',
                'ordering': ['id'],
            },
        ),
    ]
