# Generated by Django 5.2 on 2025-07-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
