# Generated by Django 5.2 on 2025-09-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_machinery_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
