# Generated by Django 5.2 on 2025-07-27 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentClassification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clasificación de Incidencia',
                'verbose_name_plural': 'Clasificaciones de Incidencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Incidencia',
                'verbose_name_plural': 'Tipos de Incidencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='obra.construction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to=settings.AUTH_USER_MODEL)),
                ('clasification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidencias.incidentclassification')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidencias.incidenttype')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-date'],
            },
        ),
    ]
