# Generated by Django 5.2 on 2025-09-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
